<a href="https://colab.research.google.com/github/Doclikam/Machine-Learning-2/blob/main/Machine-Learning-2/week3_deep%20learning/dlpractice%20/learningtensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BRAIN TUMOUR CLASSIFICATION**

we are going to learn deep learning with brain tumor classification, understanding the coding and recapping on old concepts

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [ ]:
import tensorflow as tf
from tensorflow.keras.model import Model, Sequential
from tensorflor.keras.layers import Input, Dense, Flatten, Conv2D, Dropout, MaxPooling2D, BatchNormalization, GlobalAveragePooling2D



x=tf.variable([1.,2.], dtype=tf.float64
x handle a mutable tensor which can survive during multiple execution, the trainable parameters: weights, biases are stored in tensors held in variables.

high level archietcture
1st layer:device layer: contains implementation to communicate with diffferent devices such as cpu, gpu, or tpu in the operating system.
network layer: has implementation to communicate to different machines using network protocols
2nd layer: kernel implemenations const, var,conv2d, Relu,MatMul

In [ ]:
import tensorflow as tf

# Tensorflow initialization methods

In [ ]:
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x=tf.constant(4.0, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
x=tf.constant([[3,4,5],[5,7,8]], shape=(2,3), dtype=tf.float32)
print(x)

tf.Tensor(
[[3. 4. 5.]
 [5. 7. 8.]], shape=(2, 3), dtype=float32)


In [ ]:
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
x=tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.5482195   1.0535793   1.6388694 ]
 [ 0.29554552  1.0880467  -0.45902056]
 [-0.63560665  0.45971313 -1.250507  ]], shape=(3, 3), dtype=float32)


In [ ]:
x=tf.random.uniform((2,3), minval=0, maxval=4)
print(x)


tf.Tensor(
[[1.2501464  2.422381   3.7212071 ]
 [1.1693425  0.78100395 0.46613312]], shape=(2, 3), dtype=float32)


In [ ]:
x=tf.range(8)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [ ]:
x=tf.range(start=1, limit=10, delta=3)
x=tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([1. 4. 7.], shape=(3,), dtype=float64)


In [ ]:
#mathematical operations
x=tf.constant([1,2])
y=tf.constant([3,4])
z=tf.add(x,y)
#or
z=x+y
  print(z)

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [ ]:
z=tf.subtract(x,y)
z=x-y
print(z)

tf.Tensor([-2 -2], shape=(2,), dtype=int32)


In [ ]:
z=tf.divide(x,y)
z=x/y
print(z)

tf.Tensor([0.33333333 0.5       ], shape=(2,), dtype=float64)


In [ ]:
z=tf.multiply(x,y)
z=x*y
print(z)

tf.Tensor([3 8], shape=(2,), dtype=int32)


In [ ]:
#dot product
z=tf.tensordot(x,y, axes=1)
print(z)

tf.Tensor(11, shape=(), dtype=int32)


In [ ]:
z=tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(11, shape=(), dtype=int32)


In [ ]:
z=x**5
print(z)

tf.Tensor([ 1 32], shape=(2,), dtype=int32)


In [ ]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
z=x @ y
print(z)

tf.Tensor(
[[-3.9637864  -0.550995   -1.0461249  -0.40287668]
 [ 2.9867013   1.5356514  -0.00950807  1.7823939 ]], shape=(2, 4), dtype=float32)


In [ ]:
#indexing
x=tf.constant([1,2,3,4,5,6,7])
print(x[:])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [ ]:
print(x[::-1])

tf.Tensor([7 6 5 4 3 2 1], shape=(7,), dtype=int32)


In [ ]:
#reshaping
x=tf.range(9)
z=tf.reshape(x, (3,3))
print(z)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [ ]:
x=tf.transpose(z, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


Building **Neurons**

In [11]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [12]:
#loaddataset
(x_train,y_train), (x_test,y_test)=mnist.load_data()
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [13]:
#reshape
x_train=x_train.reshape(-1,28*28).astype('float32')/255.0

In [14]:
x_test=x_test.reshape(-1,28*28).astype('float32')/255.0

In [15]:
model=tf.keras.Sequential([layers.Dense(512,activation=('relu')), layers.Dense(512, activation=('relu')), layers.Dense(10)])

In [22]:
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)

Epoch 1/5
1875/1875 - 20s - 11ms/step - accuracy: 0.9456 - loss: 0.1808
Epoch 2/5
1875/1875 - 19s - 10ms/step - accuracy: 0.9746 - loss: 0.0807
Epoch 3/5
1875/1875 - 21s - 11ms/step - accuracy: 0.9829 - loss: 0.0547
Epoch 4/5
1875/1875 - 18s - 10ms/step - accuracy: 0.9871 - loss: 0.0425
Epoch 5/5
1875/1875 - 18s - 10ms/step - accuracy: 0.9885 - loss: 0.0344


In [24]:
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9814 - loss: 0.0734


[0.07339823246002197, 0.9814000129699707]

In [ ]:
model=tf.keras.Sequential()
model.add(tf.keras.Input(shape=(784), ))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10))

model.summary()

In [33]:
#functional APi
inputs=tf.keras.Input(shape=(784, ))
x=layers.Dense(512, activation='relu')(inputs)
x=layers.Dense(256,activation='relu')(x)
output=layers.Dense(10, activation='softmax')(x)
model=tf.keras.Model(inputs=inputs, outputs=output)


model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False), optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 16s - 9ms/step - accuracy: 0.9424 - loss: 0.1864
Epoch 2/5
1875/1875 - 21s - 11ms/step - accuracy: 0.9758 - loss: 0.0779
Epoch 3/5
1875/1875 - 20s - 11ms/step - accuracy: 0.9833 - loss: 0.0535
Epoch 4/5
1875/1875 - 20s - 11ms/step - accuracy: 0.9862 - loss: 0.0410
Epoch 5/5
1875/1875 - 16s - 9ms/step - accuracy: 0.9890 - loss: 0.0332
313/313 - 1s - 3ms/step - accuracy: 0.9782 - loss: 0.0766


[0.07655492424964905, 0.9782000184059143]